#!/usr/bin/env php
<?php
/**
 * setup.php — Script inisialisasi awal cek.resource.my.id
 *
 * Jalankan sekali setelah clone/download:
 *   php setup.php
 *
 * Yang dilakukan:
 *  1. Cek requirement (PHP versi, ekstensi)
 *  2. Buat file .env dari .env.example
 *  3. Buat database dan import schema
 *  4. Buat direktori yang dibutuhkan
 *  5. Generate APP_KEY dan JWT_SECRET
 */

define('SETUP_ROOT', __DIR__);
define('SETUP_VERSION', '1.0.0');

// ─── Warna CLI ────────────────────────────────────────────────
function c(string $text, string $color = ''): string
{
    $colors = [
        'red'    => "\033[31m",
        'green'  => "\033[32m",
        'yellow' => "\033[33m",
        'blue'   => "\033[34m",
        'cyan'   => "\033[36m",
        'bold'   => "\033[1m",
        ''       => "\033[0m",
    ];
    return ($colors[$color] ?? '') . $text . "\033[0m";
}

function info(string $msg)    { echo c('  i  ', 'cyan')   . $msg . "\n"; }
function ok(string $msg)      { echo c('  v  ', 'green')  . $msg . "\n"; }
function warn(string $msg)    { echo c('  !  ', 'yellow') . $msg . "\n"; }
function fail(string $msg)    { echo c('  x  ', 'red')    . $msg . "\n"; }
function title(string $msg)   { echo "\n" . c("=== {$msg} ", 'bold') . "\n"; }
function ask(string $prompt, string $default = ''): string
{
    $hint  = $default !== '' ? " [{$default}]" : '';
    echo c('  ?  ', 'blue') . $prompt . $hint . ': ';
    $input = trim(fgets(STDIN));
    return $input !== '' ? $input : $default;
}

// ─── HEADER ───────────────────────────────────────────────────
echo "\n" . c("+-----------------------------------------+\n", 'cyan');
echo      c("|   cek.resource.my.id -- Setup v" . SETUP_VERSION . "      |\n", 'cyan');
echo      c("+-----------------------------------------+\n\n", 'cyan');

// ═══════════════════════════════════════════
// STEP 1 — Cek requirement
// ═══════════════════════════════════════════
title("STEP 1: Checking Requirements");

$allOk = true;

// PHP version
if (version_compare(PHP_VERSION, '7.4.0', '>=')) {
    ok("PHP " . PHP_VERSION);
} else {
    fail("PHP 7.4+ dibutuhkan, Anda menggunakan " . PHP_VERSION);
    $allOk = false;
}

// Required extensions
foreach (['pdo', 'pdo_mysql', 'json', 'mbstring', 'openssl'] as $ext) {
    if (extension_loaded($ext)) {
        ok("Extension {$ext}");
    } else {
        fail("Extension {$ext} tidak tersedia");
        $allOk = false;
    }
}

if (!$allOk) {
    fail("Setup gagal: requirement tidak terpenuhi.");
    exit(1);
}

// ═══════════════════════════════════════════
// STEP 2 — Buat .env
// ═══════════════════════════════════════════
title("STEP 2: Environment Configuration");

$envPath = SETUP_ROOT . '/.env';
$skipEnv = false;

if (file_exists($envPath)) {
    $overwrite = ask(".env sudah ada. Timpa? (y/N)", "N");
    if (strtolower($overwrite) !== 'y') {
        info("Melewati pembuatan .env");
        $skipEnv = true;
    }
}

if (!$skipEnv) {
    info("Masukkan konfigurasi database:");
    $dbHost = ask("DB_HOST", "localhost");
    $dbPort = ask("DB_PORT", "3306");
    $dbName = ask("DB_NAME", "cek_resource");
    $dbUser = ask("DB_USER", "root");
    $dbPass = ask("DB_PASS", "");

    $appKey    = bin2hex(random_bytes(32));
    $jwtSecret = bin2hex(random_bytes(32));
    $genDate   = date('Y-m-d H:i:s');

    $envLines = [
        "# ============================================================",
        "# cek.resource.my.id -- Environment Configuration",
        "# Generated by setup.php on {$genDate}",
        "# ============================================================",
        "",
        "APP_ENV=development",
        "",
        "DB_HOST={$dbHost}",
        "DB_PORT={$dbPort}",
        "DB_NAME={$dbName}",
        "DB_USER={$dbUser}",
        "DB_PASS={$dbPass}",
        "",
        "APP_KEY={$appKey}",
        "JWT_SECRET={$jwtSecret}",
        "",
        "UPLOAD_PATH=public/uploads",
        "UPLOAD_MAX_SIZE=5242880",
    ];

    file_put_contents($envPath, implode("\n", $envLines) . "\n");
    ok(".env berhasil dibuat");
    ok("APP_KEY   : " . substr($appKey, 0, 16) . "...");
    ok("JWT_SECRET: " . substr($jwtSecret, 0, 16) . "...");
}

// ═══════════════════════════════════════════
// STEP 3 — Import database
// ═══════════════════════════════════════════
title("STEP 3: Database Setup");

// Load .env ke variabel
$envVars = [];
if (file_exists($envPath)) {
    foreach (file($envPath) as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#' || strpos($line, '=') === false) continue;
        list($k, $v)     = explode('=', $line, 2);
        $envVars[trim($k)] = trim($v);
    }
}

$dbHost = $envVars['DB_HOST'] ?? 'localhost';
$dbPort = $envVars['DB_PORT'] ?? '3306';
$dbName = $envVars['DB_NAME'] ?? 'cek_resource';
$dbUser = $envVars['DB_USER'] ?? 'root';
$dbPass = $envVars['DB_PASS'] ?? '';

info("Mencoba koneksi ke MySQL ({$dbHost}:{$dbPort})...");

$dbOk = false;
try {
    $pdo = new PDO(
        "mysql:host={$dbHost};port={$dbPort};charset=utf8mb4",
        $dbUser,
        $dbPass,
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
    );
    ok("Koneksi MySQL berhasil");
    $dbOk = true;
} catch (PDOException $e) {
    fail("Koneksi database gagal: " . $e->getMessage());
    warn("Pastikan MySQL berjalan dan kredensial di .env sudah benar.");
    warn("Anda bisa import database.sql secara manual via phpMyAdmin.");
}

if ($dbOk) {
    $exists = $pdo->query("SHOW DATABASES LIKE '{$dbName}'")->rowCount() > 0;
    $doImport = true;

    if ($exists) {
        $reimport = ask("Database '{$dbName}' sudah ada. Import ulang schema? (y/N)", "N");
        if (strtolower($reimport) !== 'y') {
            info("Melewati import database.");
            $doImport = false;
        }
    }

    if ($doImport) {
        $sqlFile = SETUP_ROOT . '/database.sql';
        if (!file_exists($sqlFile)) {
            fail("File database.sql tidak ditemukan!");
        } else {
            info("Mengimport database.sql...");
            try {
                $sql = file_get_contents($sqlFile);
                $pdo->exec($sql);
                ok("Database '{$dbName}' berhasil diimport");
            } catch (PDOException $e) {
                fail("Import gagal: " . $e->getMessage());
                warn("Coba import database.sql secara manual via phpMyAdmin.");
            }
        }
    }
}

// ═══════════════════════════════════════════
// STEP 4 — Buat direktori
// ═══════════════════════════════════════════
title("STEP 4: Creating Directories");

$year  = date('Y');
$month = date('m');
$dirs  = [
    'public/uploads',
    "public/uploads/{$year}",
    "public/uploads/{$year}/{$month}",
    'public/assets/css',
    'public/assets/js',
    'public/assets/img',
    'logs',
    'storage/cache',
    'storage/sessions',
];

foreach ($dirs as $dir) {
    $path = SETUP_ROOT . '/' . $dir;
    if (!is_dir($path)) {
        if (mkdir($path, 0755, true)) {
            ok("Dibuat: {$dir}");
        } else {
            fail("Gagal membuat: {$dir}");
        }
    } else {
        info("Sudah ada: {$dir}");
    }
}

// Security .htaccess di uploads
$uploadsHtaccess = SETUP_ROOT . '/public/uploads/.htaccess';
if (!file_exists($uploadsHtaccess)) {
    $htContent = "Options -Indexes\n"
        . "<FilesMatch \"\\.(php|php5|phtml|asp|aspx|cgi|pl)\$\">\n"
        . "    Deny from all\n"
        . "</FilesMatch>\n";
    file_put_contents($uploadsHtaccess, $htContent);
    ok("Security .htaccess dibuat di public/uploads/");
}

// ═══════════════════════════════════════════
// STEP 5 — Selesai
// ═══════════════════════════════════════════
title("STEP 5: Done!");

$lines = [
    "+-----------------------------------------------------+",
    "|                                                     |",
    "|   Setup selesai! Langkah selanjutnya:               |",
    "|                                                     |",
    "|   1. Buka http://localhost/cek-resource/            |",
    "|   2. Login admin: admin@cek.resource.my.id          |",
    "|      Password   : Admin@1234                        |",
    "|   3. GANTI PASSWORD default segera!                 |",
    "|   4. Konfigurasi modul di /admin -> Modul           |",
    "|                                                     |",
    "+-----------------------------------------------------+",
];

echo "\n";
foreach ($lines as $line) {
    echo c($line, 'green') . "\n";
}
echo "\n";
